project:
  type: website

website:
  title: "GPU-accelerated Computing in Bioconductor"
  navbar:
    left:
      - href: overview.qmd
        text: Overview
      - href: projects.qmd
        text: Projects
      - href: commits.qmd
        text: "Recent Commits"
    right:
      - icon: github
        href: https://github.com/waldronlab/czieoss6-biocgpu

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual
